version: "3.8"
services:
  client:
    build: "./"
    container_name: gcc_container
    volumes:
      - ./:/app
    restart: always

volumes:
  container:
    name: container
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mhrima/Desktop/container