version: "3.8"
services:
  client:
    build: "./compiler"
    container_name: gcc_container
    volumes:
      - "${PWD}/compiler:/compiler"
    restart: on-failure

volumes:
  container:
    name: container
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/compiler"
